name: unit test
on:  
  push:
  pull_request:
    branches:
      - main
jobs:
  setup-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: npm ci
      - name: Run unit tests
        run: npm run test